resources:
- name: git-assets
  type: git
  source:
    branch: master
    uri: https://github.com/nsagoo-pivotal/concourse-workshop

- name: cloudfoundry
  type: cf
  source: 
    api: {{cf-api}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    username: {{cf-username}}
    password: {{cf-password}}

jobs:
- name: unit-test
  public: true
  plan:
  - get: git-assets
    trigger: true
  - task: mvn-test
    file: git-assets/ci/tasks/mvn-test.yml

- name: deploy
  public: true
  plan:
  - get: git-assets
    trigger: true
    passed:
      - unit-test
  - task: mvn-package
    file: git-assets/ci/tasks/mvn-package.yml
  - put: cloudfoundry
    params:
      manifest: git-assets/manifest.yml
      path: app-output/concourse-demo.jar
