resources:
- name: git-assets
  type: git
  source:
    uri: https://github.com/nsagoo-pivotal/concourse-workshop
    branch: master

jobs:
- name: hello
  plan:
  - get: git-assets
    trigger: true
  - task: howdy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, My first pipeline!"]
